### ISSUE TITLE
Create CI/CD Workflow

### ISSUE THREAD

**Issue by TannerBarcelos** [clew-bot/Altitude#2]
> Using GitHub Actions to achieve the build / package and deploy pipeline

##### Reference
https://github.com/marketplace/actions/deploy-to-heroku
https://dev.to/nipeshkc7/deploying-node-js-app-to-heroku-using-github-actions-3k7g

#### Create Credentials
`heroku authorizations:create`

#### Add credentials as Secrets to project
HEROKU_API_KEY = <your api key>
HEROKU_APP_NAME = <your app name>

#### Create the Action file
1. Create a .github directory at top level
2. Create a workflows directory inside that directory
3. Create a file called **deploy.yml**
4. Add the contents to the workflow file 
5. name: Deploy
```

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  deploy:
      name: Deploy
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout
          uses: actions/checkout@v1

        - name: Add remote origin
          run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

        - name: Deploy backend to heroku
          run: git push --force heroku `git subtree split --prefix server HEAD`:master
```
6. Push the server file (which also hosts static assets)
7. Create ecosystem file for Heroku config (ecosystem.config.js) at top level
```
module.exports = {
    apps : [{
      name: "matched-betting-tracker",
      script: "./index.js",
      instances: "max",
      env: {
        NODE_ENV: "development",
      },
      env_production: {
        NODE_ENV: "production",
      }
    }]
  }
```
9. Add start scripts and PM2 to run processes in prod to package.json scripts section

```
   // Other scripts
   "heroku-prebuild": "npm install pm2 -g",
   "start": "pm2-runtime start ecosystem.config.js --env production"

```
